### ISSUE TITLE
Immediately executing require statements, paths not being refactored.

### ISSUE THREAD

**Issue by jspaine** [jurassix/refactoring-codemods#9]
It doesn't work for `require('path/to/foo')()`

Also just noticed it didn't work for `import app from './app'` where ./app was a folder containing an index.js

**Comment by jurassix** [comment]
QQ: on the `path/to/foo` how do we determine the base path?

@ahutchings any thoughts here? Should we just assume root of the project? Is this even a valid require path? I can decide based on reading the NodeJS [path docs](https://nodejs.org/docs/latest/api/path.html) or [modules docs](https://nodejs.org/docs/latest/api/modules.html#modules_modules)

Moving this to a new issue:

> Also just noticed it didn't work for import app from './app' where ./app was a folder containing an index.js

**Comment by ahutchings** [comment]
The default node resolution behavior is to treat a path like `thing/to/foo` as a reference to the `thing` module in node_modules. Webpack and some other tools allow for multiple module roots to be configured, so `thing/to/foo` may go to some other arbitrary directory in your project. Because multiple of these roots can be configured, probably not safe to assume a root directory, but maybe we could pass that in as an option to the codemod?

**Comment by jspaine** [comment]
Sorry, that was supposed to be a relative path, `require('./path/to/foo')()` gets ignored.

It could be nice if it worked with webpack aliases and stuff but they break vscode intellisense so I haven't been using them.

**Comment by jurassix** [comment]
I'm surprised that `require('./path/to/foo')()` isn't working. We can fix this.
